micronaut:
  application:
    name: udemy

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              algorithm: HS256
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:12345}"'
  server:
    port: ${SERVER_PORT:8080}
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:mysql://localhost:3306/eShop
    username: mitul
    password: 61234567
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3

shedlock:
  defaults:
    lock-at-most-for: 1m